wifi_ssid: ENC[AES256_GCM,data:bAbZuUbvscg=,iv:9y0Qd6+GjTXIMCuU0xWIvuGiFGXyqfpkYLfLZriD0Tk=,tag:0ZsjTEx7meGazqPimD3WMw==,type:str]
wifi_password: ENC[AES256_GCM,data:ZgYEC621S7dKvpXtVfA0W5VTKJw=,iv:HlNicIHgaIQ0ibxO68/tShIvBoKcudvBwigCOYscLfQ=,tag:y0HYuEAV/DB00Mw3BBEfHw==,type:str]
api_encryption_key: ENC[AES256_GCM,data:KXcN1mFT9xdncdjmcvL6tWA60UGTYfrymw9L04NmWoUJnvb3+6q12SUUQIc=,iv:7ROiTxBUH+bVmtFrufpirc8zUvzn6CzQd9wmBlLlKrM=,tag:L0BZ0rOh4bFBbL0Wd0sGxA==,type:str]
ota_password: ENC[AES256_GCM,data:hOvtygugiQLuPH87GNhleGKg3hUQxw7Q4MBulh8qT+0=,iv:DZtg0ZThoK6MykQgJSUfeEic3YMW38NaUO3vhHOPcmg=,tag:WUzC+9rsIOkEM7CgR8tDtA==,type:str]
wifi_ap_password: ENC[AES256_GCM,data:U1VpzEvmJTknmuDi,iv:GMB1PMKxkI4Se7cyiR553mQHjcQWbvlg/Ad23FMQmP4=,tag:I8w2rv/nc5LPXocbbU3Vdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yzv39q3t3zaykftaqzkzkxu8qzf242r3f2az4qxt94k47995nqvsd0qwfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOEh1bHJ0LzdSZXZBV2ZE
            b3NLODhWKyt1VTExWnlVend1S2oxcjVrV0NFCklWNUJJYmZFUUdORGJrYkE2OHl4
            cUk3bno4bTBUVzJJdTMwOU9oYi9UT28KLS0tIC9ycWV2eElQYU1HejMrc1Uxa3ZM
            SEVMMDVpeThZZjZqdEJnSUk3MDhML00Kp3XNCzQkdgez2INgBPF/D0B286/ds9jB
            +O/iUqLWcCiMrdzh4PB9o0K7+bk8qx8s8owqDmw0H3BAd4J+zCvjEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T05:23:27Z"
    mac: ENC[AES256_GCM,data:6GjOzl7uorQ103OwddCY/u3Ke3W6g4PmBheU7Q2uENUKgsbGT5Po/zWDsFnY9FMUjcamjdBf+NXn6VeT0kY46e555xQtYPHfnqQdsHrg2k9GVQT3e8Arc01zQPUtBkek4WYSLXABYKC6T7f5qJ4AWuWOiPo69w8FfEnp0/6KXyY=,iv:Dvq10TnvP47XJgmQ+vEEEIXMdh9r775TfrGIoeVcXyM=,tag:Z/11bWdDOOb4bquMYNt4Fw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
